apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    secureJsonData: {}

  - name: Prometheus-HA
    type: prometheus
    access: proxy
    url: http://prometheus-ha:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    secureJsonData: {}

  - name: Prometheus-Upgrade
    type: prometheus
    access: proxy
    url: http://prometheus-upgrade:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 10s
      queryTimeout: 60s
      httpMethod: POST
    secureJsonData: {}